server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /emos-wx-api

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    database: 0
    host: 192.168.224.128
#        host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  data:
    mongodb:
      host: localhost
      port: 27017
      database: emos
      authentication-database: admin
      username: admin
      password: abc123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.emos.wx.db.dao : warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"

emos:
  jwt:
    secret: abc123456
    expire: 5
    cache-expire: 10
  face:
    createFaceModelUrl: http://192.168.224.128:3000/create_face_model
#        createFaceModelUrl: http://localhost:3000/create_face_model
    checkinUrl: http://192.168.224.128:3000/checkin
#        checkinUrl: http://localhost:3000/checkin
  image-folder: F:/emos/image
#    image-folder: /root/emos/image
  code: HelloWorld
  recieveNotify: http://192.168.1.40:8080/emos-wx-api/meeting/recieveNotify
#    recieveNotify: http://localhost:8080/emos-wx-api/meeting/recieveNotify

workflow:
  url: http://192.168.224.128:9090/emos-workflow
#    url: http://localhost:9090/emos-workflow
wx:
  app-id: wxd63c53f8a7c330ff
  app-secret: 17ea0d97af2d84d4a29a3450cc7aae38
##下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
##指定Mybatis的实体目录
#mybatis.type-aliases-package=com.example.emos.wx.api.mybatis.entity
## 应用服务 WEB 访问端口
#server.port=8080

